services:
  backend-dev-test:
    build: .
    network_mode: host
    #ports:
    #  - "5000:5000"
    environment:
      SPRING_ACTIVE_PROFILES: default, production
      SERVER_PORT: 5000
      #PRODUCTS_REPOSITORY_HOST: simulado
      #PRODUCTS_REPOSITORY_PORT: 80
      PRODUCTS_REPOSITORY_HOST: localhost
      PRODUCTS_REPOSITORY_PORT: 3001
