services:
  server:
    build: .
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_ACTIVE_PROFILE: development
      SERVER_PORT: 5000
      PRODUCTS_REPOSITORY_HOST: host.docker.internal
      PRODUCTS_REPOSITORY_PORT: 3001

