services:
  backend-dev-test:
    image: backend-dev-test:latest
    build: .
    environment:
      SPRING_ACTIVE_PROFILE: development
      SERVER_PORT: 5000
      # PRODUCTS_REPOSITORY_HOST: simulado
      # PRODUCTS_REPOSITORY_PORT: 80
      PRODUCTS_REPOSITORY_HOST: localhost
      PRODUCTS_REPOSITORY_PORT: 3001
    # Enable for network_mode other than host
    # ports:
    #   - "5000:5000"
    network_mode: host
