---
application:
  enable:
    # Allows CORS requests from all domains
    publicAPI: true

products:
  repository:
    external:
      host: localhost
      port: 3001
      connectionTimeoutSeconds: 1
